name: Containerize-Push-DockerHub

on: 
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v2
    - run: |
        pip install -r requirements_push.txt
        python train.py
        bentoml build --version cicd
        bentoml list
        bentoml containerize wine_classifier:cicd -t onvsoff/wine_cicd
        docker push onvsoff/wine_cicd
