name: model-wine-quality
on: 
  push:
    branches: [master]
    
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/setup-python@v2
      - name: Install BentoML
        run: |
            sudo apt-get install python-dev
            pip install -r https://raw.githubusercontent.com/bentoml/gallery/main/quickstart/requirements.txt


