name: model-wine-quality
on: 
  push:
    branches: [master]
    
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/setup-python@v2
      - name: Install BentoML
        run: |
            bentoml --version


