name: model-wine-quality
on: 
  push:
    branches: [master]
    
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - name: Install BentoML
      - run: |
          pip install bentoml
          bentoml --version


