name: model-wine-quality
on: 
  push:
    branches: [master]
    
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/setup-python@v2
      - name: Install BentoML
        run: |
          pip install bentoml
          bentoml --version


