name: CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v2
    - run: |
        pip install -r requirements.txt
        python train.py
        bentoml build --version cicd
        bentoml list
        bentoml containerize iris_classifier:cicd -t onvsoff/iris_cicd
        docker push onvsoff/iris_cicd
